### ISSUE TITLE
getting API - not running HA in Docker

### ISSUE THREAD

**Issue by synlink** [0xAlon/tami4edge#2]
hello Alon, 
thanks for your contribution.
i am not sure how to get the API keys, i am not running my HA in docker container.
those commands do not work in CLI.
appreciate the assistance.
thanks.

**Comment by ZshlomiA4** [comment]
Hi,
same here.
i"m running HA as VM in ESXI,
couldn't run those commands.

waiting for a reply :)
i really want to connect Tami4 to HA
![image](https://user-images.githubusercontent.com/35681247/188099169-0a1966fe-9fbc-4ff0-a3e2-35e6115cb362.png)

**Comment by kamaln7** [comment]
You only need to run the token extractor once to get the token so you can then copy it to HA's config file. So you can just run it on your computer.

But, if you still want to run it within the HA OS, use the `login` command in the `ha >` prompt to drop into an actual shell where you can run the `docker pull` & `docker run` commands in the readme. Once you're done you can run `exit` to go back to the HA CLI.

**Comment by ZshlomiA4** [comment]
@kamaln7 , thank you for the comment,
I managed to get the API key,
but I get an error after following the rest of the instructions:

placing this in the configuration.yaml file:
![image](https://user-images.githubusercontent.com/35681247/196501890-e5818341-d68c-4906-bf33-47a2b8dac845.png)

this is the error

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/tami4edge/API/API.py:49
Integration: tami4edge
First occurred: 8:18:23 PM (1 occurrences)
Last logged: 8:18:23 PM

Error during setup of component tami4edge
Traceback (most recent call last):
  File "/config/custom_components/tami4edge/API/API.py", line 39, in _send_post_request
    json_resp = await resp.json(content_type=None)
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 52, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/tami4edge/__init__.py", line 52, in async_setup
    await client.refresh_token()
  File "/config/custom_components/tami4edge/API/API.py", line 80, in refresh_token
    response = await self._send_post_request(data=data, api='/public/token/refresh')
  File "/config/custom_components/tami4edge/API/API.py", line 49, in _send_post_request
    raise Tami4EdgeApiError(
custom_components.tami4edge.API.API.Tami4EdgeApiError: Recieved invalid response from API: unexpected character: line 1 column 1 (char 0)
