### ISSUE TITLE
Sending the OTP fails

### ISSUE THREAD

**Issue by maozroy** [0xAlon/tami4edge#4]
After sending the OTP i am getting a parsing error. any idea?
```

 docker run -it 0xalon/tami4edgecloudtokenextractor:latest

/usr/local/lib/python3.8/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
What's your phone number to sign up? <+972XXXXXXXXX>: 05222222
OTP: 1234
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 37, in <module>
    response = submit_otp(phone_number, otp)
  File "main.py", line 23, in submit_otp
    response = requests.post(
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by liorpapir** [comment]
I'm having the same issue.
The docker worked well a few months ago, but I had to replace my Tami4Edge device, and now I'm not able to retrieve the key :(

**Comment by semash1** [comment]
same for me :(

**Comment by alws34** [comment]
I also cant get the key...
same error as @maozroy
hope this will be fixed soon 
* using HA container (v 2024.1.3)
