### ISSUE TITLE
API calls - issue

### ISSUE THREAD

**Issue by semash1** [0xAlon/tami4edge#7]
Hi Alon,
Thank you for the project! 
Any chance to update tami4edge for Home Assistant?

➜  ~ docker pull 0xalon/tami4edgecloudtokenextractor:latest 
latest: Pulling from 0xalon/tami4edgecloudtokenextractor
Digest: sha256:1d0e17f6141216430e3c8ac3c73c8bb711b0cd78e8a993f6644a20b34903c90a
Status: Image is up to date for 0xalon/tami4edgecloudtokenextractor:latest
docker.io/0xalon/tami4edgecloudtokenextractor:latest
➜  ~ docker run -it 0xalon/tami4edgecloudtokenextractor:latest
/usr/local/lib/python3.8/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
What's your phone number to sign up? <+972XXXXXXXXX>: xxxxxxxxx
OTP: XXXX
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 37, in <module>
    response = submit_otp(phone_number, otp)
  File "main.py", line 23, in submit_otp
    response = requests.post(
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by leranp** [comment]
Same here, any workaround

**Comment by gshlomi** [comment]
any news on the issue?

**Comment by leranp** [comment]
> any news on the issue?

You can use this repository to get the token:
https://github.com/Guy293/Tami4EdgeAPI
