### ISSUE TITLE
Buttons are not loaded

### ISSUE THREAD

**Issue by leranp** [0xAlon/tami4edge#9]
Hi,

I now have a new tami4edge device and I used  this repository (https://github.com/Guy293/Tami4EdgeAPI) to pull the token of my user , all the entities (sensors ,services) are working fine , but I don't have the buttons .

this is the error message from the integration:
```
Logger: homeassistant.components.button
Source: custom_components/tami4edge/button.py:17
Integration: Button ([documentation](https://www.home-assistant.io/integrations/button), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+button%22))
First occurred: 6:53:02 PM (1 occurrences)
Last logged: 6:53:02 PM

Error while setting up tami4edge platform for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tami4edge/button.py", line 17, in async_setup_platform
    waterConsumptionCoordinator = hass.data[DOMAIN_DATA]['waterConsumptionCoordinator']
                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'waterConsumptionCoordinator'
```

**Comment by leranp** [comment]
it is only me?

**Comment by taltaub22** [comment]
What version of HA are you using?

**Comment by leranp** [comment]
> What version of HA are you using?

Now 2023.9.2, but the issue was in 2023.8.0-3

**Comment by leranp** [comment]
I added a service to boil the water 
https://github.com/taltaub22/tami4edge/pull/1
